<?php

/**
*
* Adress
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Adress extends Entity {
    public $adressFacture;     // varchar(45)
    public $adressLivraison;     // varchar(45)
    public $user_id;     // int
    public $user_panier_id;     // int

    public function __construct(
        $adressFacture = "",
        $adressLivraison = "",
        $user_id = "",
        $user_panier_id = "",
    $id = false) {
        parent::__construct($id);

        $this->adressFacture = $adressFacture;
        $this->adressLivraison = $adressLivraison;
        $this->user_id = $user_id;
        $this->user_panier_id = $user_panier_id;
    }
}
?>
