<?php

/**
*
* Categorie
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Categorie extends Entity {
    public $nom;     // varchar(45)

    public function __construct(
        $nom = "",
    $id = false) {
        parent::__construct($id);

        $this->nom = $nom;
    }
}
?>
