<?php

/**
*
* Commentaire
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Commentaire extends Entity {
    public $message;     // varchar(255)
    public $auteur;     // varchar(45)
    public $date;     // date
    public $etoile;     // varchar(45)
    public $produit_id;     // int
    public $produit_souscategorie_id;     // int
    public $produit_souscategorie_categorie_id;     // int

    public function __construct(
        $message = "",
        $auteur = "",
        $date = "",
        $etoile = "",
        $produit_id = "",
        $produit_souscategorie_id = "",
        $produit_souscategorie_categorie_id = "",
    $id = false) {
        parent::__construct($id);

        $this->message = $message;
        $this->auteur = $auteur;
        $this->date = $date;
        $this->etoile = $etoile;
        $this->produit_id = $produit_id;
        $this->produit_souscategorie_id = $produit_souscategorie_id;
        $this->produit_souscategorie_categorie_id = $produit_souscategorie_categorie_id;
    }
}
?>
