<?php

/**
*
* Extrait
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Extrait extends Entity {
    public $titre;     // varchar(45)
    public $duree;     // datetime
    public $prix;     // float
    public $medias;     // varchar(45)
    public $produit-musique_id;     // int
    public $produit-musique_produit_id;     // int
    public $produit_musique_produit_sous-categorie_id;     // int
    public $produit-musique_produit_sous-categorie_categorie_id;     // int

    public function __construct(
        $titre = "",
        $duree = "",
        $prix = "",
        $medias = "",
        $produit-musique_id = "",
        $produit-musique_produit_id = "",
        $produit_musique_produit_sous-categorie_id = "",
        $produit-musique_produit_sous-categorie_categorie_id = "",
    $id = false) {
        parent::__construct($id);

        $this->titre = $titre;
        $this->duree = $duree;
        $this->prix = $prix;
        $this->medias = $medias;
        $this->produit-musique_id = $produit-musique_id;
        $this->produit-musique_produit_id = $produit-musique_produit_id;
        $this->produit_musique_produit_sous-categorie_id = $produit_musique_produit_sous-categorie_id;
        $this->produit-musique_produit_sous-categorie_categorie_id = $produit-musique_produit_sous-categorie_categorie_id;
    }
}
?>
