<?php

/**
*
* Panier
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Panier extends Entity {
    public $fdp;     // varchar(45)
    public $user_id;     // int

    public function __construct(
        $fdp = "",
        $user_id = "",
    $id = false) {
        parent::__construct($id);

        $this->fdp = $fdp;
        $this->user_id = $user_id;
    }
}
?>
