<?php

/**
*
* Souscategorie
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Souscategorie extends Entity {
    public $nom;     // varchar(45)
    public $description;     // varchar(255)
    public $genre;     // varchar(45)
    public $categorie_id;     // int

    public function __construct(
        $nom = "",
        $description = "",
        $genre = "",
        $categorie_id = "",
    $id = false) {
        parent::__construct($id);

        $this->nom = $nom;
        $this->description = $description;
        $this->genre = $genre;
        $this->categorie_id = $categorie_id;
    }
}
?>
