<?php

/**
*
* Stock
*
* This class was generated by a script. Please be careful changing it.
* Regenerate it will erase all changes!
*/

namespace App\Models\Tables;

use Helpers\DB\Entity;

class Stock extends Entity {
    public $quantite;     // int
    public $arrivage;     // varchar(45)

    public function __construct(
        $quantite = "",
        $arrivage = "",
    $id = false) {
        parent::__construct($id);

        $this->quantite = $quantite;
        $this->arrivage = $arrivage;
    }
}
?>
